### ISSUE TITLE
deployment fails with error "TypeError: no _dump_data is defined for class Thread::Mutex" by using sshkit 1.11+

### ISSUE THREAD

**Issue by dkd-ebert** [dkdeploy/dkdeploy-typo3-cms#10]
deployment fails with Error "TypeError: no _dump_data is defined for class Thread::Mutex" by using sshkit versions 1.11-11.15. 

cap aborted!
TypeError: no _dump_data is defined for class Thread::Mutex

Tasks: TOP => deploy:set_current_revision
(See full trace by running task with --trace)
The deploy has failed with an error: no _dump_data is defined for class Thread::Mutex
00:47 deploy:failed
      ERROR Error occurred at deployment. Rollback to old release
/Users/dimitriebert/.rvm/gems/ruby-2.3.5/gems/capistrano-3.9.1/lib/capistrano/dsl.rb:70:in 'dump': no _dump_data is defined for class Thread::Mutex (TypeError)

Related to this commit https://github.com/capistrano/sshkit/commit/27b88cab9d3978802890263a8e0e23d77ac2772e

It results Thread::Mutex data in release_roles and can not be serialized by capistrano

**Comment by websi** [comment]
This is a dkdeploy-core issue.
I created a new ticket dkdeploy/dkdeploy-core#39
